// Generated by prepare_actions.py. Original PNG poses + original WebP timing.
(function(root,factory){if(typeof module==="object"&&module.exports)module.exports=factory();else root.PhiloActionAssets=factory();})(typeof globalThis!=="undefined"?globalThis:this,function(){return {
  "run": {
    "src": "./assets/actions/run.png",
    "frameWidth": 512,
    "frameHeight": 420,
    "columns": 4,
    "rows": 3,
    "frameCount": 12,
    "renderScale": 0.58,
    "anchor": [
      265,
      355
    ],
    "posterFrame": 0,
    "duration": 1000,
    "timeline": [
      {
        "frame": 0,
        "duration": 90
      },
      {
        "frame": 1,
        "duration": 80
      },
      {
        "frame": 2,
        "duration": 80
      },
      {
        "frame": 3,
        "duration": 90
      },
      {
        "frame": 4,
        "duration": 80
      },
      {
        "frame": 5,
        "duration": 80
      },
      {
        "frame": 6,
        "duration": 90
      },
      {
        "frame": 7,
        "duration": 80
      },
      {
        "frame": 8,
        "duration": 80
      },
      {
        "frame": 9,
        "duration": 90
      },
      {
        "frame": 10,
        "duration": 80
      },
      {
        "frame": 11,
        "duration": 80
      }
    ],
    "sourceHashes": {
      "frame-00.png": "f60f41bb578709a85b6131c3123cacbb93824c822ff4b2088eccff3e4f7315cb",
      "frame-01.png": "f2300ddeed320c6d14d3d8e94a8f9a1990b2040531b289d8208af9acf34743bf",
      "frame-02.png": "ccddd820cdc2b76bc6b54ce3a9f1ade0be62df292634f1eba4610f25832804a0",
      "frame-03.png": "a7143b1fb25567d2998c3624bc9f5cda4c2bacde043e7a0c45171a937a513a06",
      "frame-04.png": "f7e8354a7eb40fc25b23bb350439b367be8c869d4b3a8630d866d056fde5144d",
      "frame-05.png": "0859f6316d45185b37faa6b7be12080ea95b117104c79364258ba78b65827d24",
      "frame-06.png": "3a563f3b0e832ab17e19afff7807f2d036f9d2d43e8f1ba78c5fd2b4f8cac318",
      "frame-07.png": "f071603b98d4649f46fecf65cc5dc6b721819205604f379112186fb41548fa9f",
      "frame-08.png": "3badf65fdb9c98c2e58169aa1d020c8ef815d738bf2b5bbfb224a712d66c4a66",
      "frame-09.png": "5d5d1c8986904e2ecb976e3115022ede655c0361278e1059940f5c0af784d193",
      "frame-10.png": "aa0bcd84b58636461a230fee89bfd5ffba97f9aaa538242f3640900226460426",
      "frame-11.png": "0ce63d238bcb8be3a327ab7c691b7fc84e2c25a37a6dd11466e174f8fd1851c6"
    }
  },
  "scratch": {
    "src": "./assets/actions/scratch.png",
    "frameWidth": 480,
    "frameHeight": 480,
    "columns": 4,
    "rows": 4,
    "frameCount": 16,
    "renderScale": 0.58,
    "anchor": [
      220,
      404
    ],
    "posterFrame": 8,
    "duration": 5880,
    "timeline": [
      {
        "frame": 0,
        "duration": 600
      },
      {
        "frame": 1,
        "duration": 140
      },
      {
        "frame": 2,
        "duration": 160
      },
      {
        "frame": 3,
        "duration": 220
      },
      {
        "frame": 4,
        "duration": 170
      },
      {
        "frame": 5,
        "duration": 300
      },
      {
        "frame": 6,
        "duration": 140
      },
      {
        "frame": 7,
        "duration": 120
      },
      {
        "frame": 8,
        "duration": 120
      },
      {
        "frame": 9,
        "duration": 120
      },
      {
        "frame": 10,
        "duration": 120
      },
      {
        "frame": 11,
        "duration": 120
      },
      {
        "frame": 12,
        "duration": 120
      },
      {
        "frame": 13,
        "duration": 120
      },
      {
        "frame": 8,
        "duration": 120
      },
      {
        "frame": 9,
        "duration": 120
      },
      {
        "frame": 10,
        "duration": 120
      },
      {
        "frame": 11,
        "duration": 120
      },
      {
        "frame": 12,
        "duration": 120
      },
      {
        "frame": 13,
        "duration": 120
      },
      {
        "frame": 8,
        "duration": 120
      },
      {
        "frame": 9,
        "duration": 120
      },
      {
        "frame": 10,
        "duration": 120
      },
      {
        "frame": 11,
        "duration": 120
      },
      {
        "frame": 12,
        "duration": 120
      },
      {
        "frame": 13,
        "duration": 120
      },
      {
        "frame": 14,
        "duration": 320
      },
      {
        "frame": 15,
        "duration": 1550
      }
    ],
    "sourceHashes": {
      "frame-00.png": "23ff40fa137f72ea788e7a84897b26643cc2dac57e0befd7c648f6fb6973d6e1",
      "frame-01.png": "c0078f8707f7714885a6201cc5f8f19348dbd3ae8a47057dc1168c705ec8e94a",
      "frame-02.png": "16dfcd98b857aca2dbe0eff1ba0b0eebc1be87ad9cbd89b299fecb680f50a636",
      "frame-03.png": "bb1d6bd3ee92fed655cc9554e7b40a501eae507a13195ef62f95a8ac641af673",
      "frame-04.png": "d1c69796c6d6f385ed1de1e0a4563f22bed56a4f270f98279efec2f38835150a",
      "frame-05.png": "c24ae314371e0e0776714cecdcd97a42cccc0d6044830db721187eea98046649",
      "frame-06.png": "d99f64fdf386b2dbb6b40035d894c8881ff4f6ddef50ba384101ad953abe35f5",
      "frame-07.png": "381208ad8f4c01b2a5cd22df4e15b1a050e7af38dcf6a014d4533fa60ab92770",
      "frame-08.png": "c00b11d61889d5fc79c7d6e7a2e7d2935e15eb049c3c2c0d879583c7a303c952",
      "frame-09.png": "b588a63edf57fb49e8b31c6d5369ebfe8cdb75eb96cfa0119ba115701d97637f",
      "frame-10.png": "76cbaeeb19c3dc4ac359fb69bf168f863ec123ee1e02535e87372cecb9b90500",
      "frame-11.png": "d2b2553f36000187e681e1cc0183e55ab9aabb3fdcd59905dc66bdf16f5d967b",
      "frame-12.png": "e3585bb22e0d19a6a334da892c5ab12a91ca716178019121c350aff556d78d68",
      "frame-13.png": "9ccf3eefd67cc164d059142cb4531a3f35da5a8b8f1fdcc05a7340b3c0af3583",
      "frame-14.png": "baee3a4158832ff9f3a689baed67aa21eee88b62d94bf922b55c3e701d0fc597",
      "frame-15.png": "3f5f2621399a87ce8b89acf6232df53624bcaff3a00f07a4818b1babdeb6bea5"
    }
  }
};});
