"""Create transparent action atlases from user-supplied frames, preserving timing.

Run with the bundled Python (Pillow and NumPy). Originals are only read.
"""
from pathlib import Path
import hashlib
import json

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT.parents[1] / 'xiaoshu-new-actions'
OUTPUT = ROOT / 'assets' / 'actions'
SPECS = {
    'run': {'animation': 'xiaoshu-four-paw-run', 'anchor': [265, 355], 'posterFrame': 0},
    'scratch': {'animation': 'xiaoshu-hat-off-scratch', 'anchor': [220, 404], 'posterFrame': 8},
}


def remove_exterior_white(image):
    rgb = np.asarray(image.convert('RGB'))
    low = rgb.min(axis=2)
    high = rgb.max(axis=2)
    # Flood only the exterior: white fur and enclosed eye regions stay opaque.
    eligible = (low >= 200) & ((high.astype(int) - low) < 35)
    flood = Image.fromarray((eligible * 255).astype('uint8')).copy()
    ImageDraw.floodfill(flood, (0, 0), 128)
    exterior = np.asarray(flood) == 128
    inside = ~exterior
    outside_near = np.asarray(Image.fromarray((inside * 255).astype('uint8')).filter(ImageFilter.MaxFilter(3))) > 0
    inside_near = np.asarray(Image.fromarray((exterior * 255).astype('uint8')).filter(ImageFilter.MaxFilter(3))) > 0
    # Unmatte the black outline's antialias pixels instead of leaving a white rim.
    edge = (exterior & outside_near & (low < 254)) | (inside & inside_near)
    alpha = np.where(exterior, 0, 255).astype('uint8')
    alpha[edge] = 255 - low[edge]
    color = rgb.copy()
    a = (alpha[edge].astype(float) / 255)[:, None]
    color[edge] = np.clip((rgb[edge].astype(float) - 255 * (1-a)) / np.maximum(a, 1/255), 0, 255).round().astype('uint8')
    color[alpha == 0] = 0
    output = Image.fromarray(np.dstack((color, alpha)))
    assert alpha[0, 0] == 0
    assert np.all(alpha[inside & ~edge] == 255)
    return output


def fingerprint(image):
    return np.asarray(image.convert('RGB').resize((96, 96)), dtype=np.float32)


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest = {}
    previews = []
    for name, spec in SPECS.items():
        paths = sorted((SOURCE / 'frames' / name).glob('frame-*.png'))
        originals = [Image.open(p).convert('RGBA') for p in paths]
        fingerprints = np.stack([fingerprint(im) for im in originals])
        animation = Image.open(SOURCE / 'animations' / (spec['animation'] + '.webp'))
        timeline = []
        for index in range(animation.n_frames):
            animation.seek(index)
            animation.load()
            distances = np.mean((fingerprints - fingerprint(animation)) ** 2, axis=(1, 2, 3))
            nearest = int(np.argmin(distances))
            if distances[nearest] > 30:
                raise ValueError(f'{name}: cannot confidently match animation frame {index}')
            timeline.append({'frame': nearest, 'duration': animation.info['duration']})
        clean = [remove_exterior_white(im) for im in originals]
        w, h = clean[0].size
        cols = 4
        rows = (len(clean) + cols - 1) // cols
        atlas = Image.new('RGBA', (w * cols, h * rows))
        for index, frame in enumerate(clean):
            atlas.paste(frame, ((index % cols) * w, (index // cols) * h))
        atlas.save(OUTPUT / (name + '.png'), optimize=True)
        manifest[name] = {
            'src': f'./assets/actions/{name}.png', 'frameWidth': w, 'frameHeight': h,
            'columns': cols, 'rows': rows, 'frameCount': len(clean),
            'renderScale': 0.58, 'anchor': spec['anchor'], 'posterFrame': spec['posterFrame'],
            'duration': sum(item['duration'] for item in timeline), 'timeline': timeline,
            'sourceHashes': {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
        }
        for i in range(len(clean)):
            panel = Image.new('RGBA', (220, 235), '#426c76')
            thumb = clean[i].copy()
            thumb.thumbnail((205, 205))
            panel.alpha_composite(thumb, ((220-thumb.width)//2, 10))
            ImageDraw.Draw(panel).text((8, 217), f'{name} / {i:02}', fill='white')
            previews.append(panel)
        print(f'{name}: {len(clean)} source frames, {len(timeline)} timed steps, {manifest[name]["duration"]} ms')
        print('timeline:', [(t['frame'], t['duration']) for t in timeline])
    data = json.dumps(manifest, ensure_ascii=False, indent=2)
    (ROOT / 'action-assets.js').write_text(
        '// Generated by prepare_actions.py. Original PNG poses + original WebP timing.\n'
        '(function(root,factory){if(typeof module==="object"&&module.exports)module.exports=factory();'
        'else root.PhiloActionAssets=factory();})(typeof globalThis!=="undefined"?globalThis:this,'
        'function(){return ' + data + ';});\n', encoding='utf-8')
    sheet = Image.new('RGBA', (220*7, 235*4), '#426c76')
    for i, panel in enumerate(previews):
        sheet.paste(panel, ((i % 7)*220, (i // 7)*235))
    sheet.convert('RGB').save('/tmp/philo-actions-transparency.jpg', quality=94)


if __name__ == '__main__':
    main()
